export const masterData2024: MasterData = {
  'Dinesh Kanna' : [
    'Rahul Chahar',
    'Harshal Patel',
    'Axar Patel',
    'Rahmanullah Gurbaz',
    'David Miller',
    'Shubman Gill',
    'Abhishek Sharma',
    'Matheesha Pathirana',
    'Nicholas Pooran',
    'Krunal Pandya',
    'Marcus Stoinis',
    'Shamar Joseph',
    'Suryakumar Yadav',
    'Hardik Pandya',
    'Rajat Patidar',
    'Moeen Ali',
    'Akash Madhwal',
    'Prasidh Krishna',
    'Anuj Rawat',
    'Umesh Yadav'
  ],
  'Kiren' : [
    'Shikhar Dhawan',
    'Nathan Ellis',
    'Mitchell Marsh',
    'Khaleel Ahmed',
    'Mukesh Kumar',
    'Harry Brook',
    'Suyash Sharma',
    'Sunil Narine',
    'Noor Ahmad',
    'Heinrich Klaasen',
    'Pat Cummins',
    'K L Rahul',
    'Ishan Kishan',
    'Glenn Maxwell',
    'Sameer Rizvi',
    'Jason Roy',
    'Harshit Rana',
    'Travis Head',
    'Nuwan Thushara',
    'Rovman Powell'
  ],
  'Yeshwant' : [
    'Liam Livingstone',
    'Harpreet Brar',
    'Rishabh Pant',
    'Chetan Sakariya',
    'Rahul Tewatia',
    'Spencer Johnson',
    'T Natarajan',
    'MS Dhoni',
    'Ajinkya Rahane',
    'Maheesh Theekshana',
    'Devdutt Padikkal',
    'Tim David',
    'Nehal Wadhera',
    'Ravichandran Ashwin',
    'Virat Kohli',
    'Atharva Taide',
    'Ramandeep Singh',
    'Kane Williamson',
    'Vijay Shankar',
    'Daryl Mitchell'
  ],
  'Shashank' : [
    'Arshdeep Singh',
    'Rinku Singh',
    'Shreyas Iyer',
    'Aiden Markram',
    'Bhuvneshwar Kumar',
    'Wanindu Hasaranga',
    'Ravindra Jadeja',
    'Rachin Ravindra',
    'Piyush Chawla',
    'Gerald Coetzee',
    'Dilshan Madushanka',
    'Jos Buttler',
    'Yashasvi Jaiswal',
    'Dinesh Karthik',
    'Cameron Green',
    'Shimron Hetmyer',
    'Trent Boult',
    'Nandre Burger',
    'Akash Deep',
    'Yash Dayal'
  ],
  'Roshan + Naveen' : [
    'Sam Curran',
    'Kagiso Rabada',
    'Prithvi Shaw',
    'Kuldeep Yadav',
    'Nitish Rana',
    'Andre Russell',
    'Mohit Sharma',
    'Shahrukh Khan',
    'Rahul Tripathi',
    'Shivam Dube',
    'Shardul Thakur',
    'Quinton De Kock',
    'Shivam Mavi',
    'Rohit Sharma',
    'Jason Behrendorff',
    'Mayank Agarwal',
    'Avesh Khan',
    'Adam Zampa',
    'Alzarri Joseph',
    'Karn Sharma'
  ],
  'Sujeeth + Siddharth' : [
    'Jitesh Sharma',
    'Jonny Bairstow',
    'Rilee Rossouw',
    'David Warner',
    'Lungi Ngidi',
    'Venkatesh Iyer',
    'Mitchell Starc',
    'Sai Sudharsan',
    'Washington Sundar',
    'Deepak Chahar',
    'Ravi Bishnoi',
    'Tilak Varma',
    'Yuzvendra Chahal',
    'Faf Du Plessis',
    'Deepak Hooda',
    'Lockie Ferguson',
    'Vijaykumar Vyshak',
    'Yudhvir Singh',
    'Mayank Dagar',
    'Shahbaz Ahmed'
  ],
  'Vasikaran' : [
    'Simran Singh',
    'Chris Woakes',
    'Anrich Nortje',
    'Varun Chakaravarthy',
    'Wriddhiman Saha',
    'Rashid Khan',
    'Abdul Samad',
    'Marco Jansen',
    'Ruturaj Gaikwad',
    'Ayush Badoni',
    'Naveen-Ul-Haq',
    'Jasprit Bumrah',
    'Sanju Samson',
    'Dhruv Jurel',
    'Mohammed Siraj',
    'Kumar Kushagra',
    'Mujeeb Ur Rahman',
    'Matthew Wade',
    'Umran Malik',
    'Mohsin Khan'
  ],
}
export const masterData2023: MasterData = {
  'Dinesh Kanna': [
    'K L Rahul',
    'Trent Boult',
    'Suryakumar Yadav',
    'Tilak Varma',
    'Ravi Bishnoi',
    'Bhuvneshwar Kumar',
    'Tim David',
    'Sarfaraz Khan',
    'Reece Topley',
    'Wanindu Hasaranga',
    'Marcus Stoinis',
    'Ramandeep Singh',
    'Kuldeep Sen',
    'Arshad Khan',
    'Rahmanullah Gurbaz',
    'Tushar Deshpande',
  ],
  Yeshwant: [
    'Ishan Kishan',
    'Varun Chakaravarthy',
    'Virat Kohli',
    'Devon Conway',
    'Anrich Nortje',
    'Chetan Sakariya',
    'Matthew Wade',
    'Rajat Patidar',
    'Maheesh Theekshana',
    'Andre Russell',
    'Venkatesh Iyer',
    'Harpreet Brar',
    'Navdeep Saini',
    'Hrithik Shokeen',
    'Aman Khan',
  ],
  Siddharth: [
    'Sanju Samson',
    'Sunil Narine',
    'Prithvi Shaw',
    'David Miller',
    'Josh Hazlewood',
    'Sai Kishore',
    'Shahrukh Khan',
    'Ambati Rayudu',
    'Shivam Mavi',
    'Glenn Maxwell',
    'Moeen Ali',
    'Anuj Rawat',
    'Jaydev Unadkat',
    'Murugan Ashwin',
  ],
  Roshan: [
    'Dinesh Karthik',
    'Rashid Khan',
    'Rohit Sharma',
    'Rahul Tripathi',
    'Arshdeep Singh',
    'Mustafizur Rahman',
    'Manish Pandey',
    'Bhanuka Rajapaksa',
    'Amit Mishra',
    'Ben Stokes',
    'Shakib Al Hasan',
    'Ravichandran Ashwin',
    'Ayush Badoni',
    'Akash Deep',
    'Mark Wood',
  ],
  'Kiren Kumar': [
    'Jos Buttler',
    'Mohammed Siraj',
    'Shikhar Dhawan',
    'Yashasvi Jaiswal',
    'Lockie Ferguson',
    'Alzarri Joseph',
    'Rinku Singh',
    'Harry Brook',
    'Khaleel Ahmed',
    'Ravindra Jadeja',
    'Deepak Hooda',
    'Abhishek Sharma',
    'Jason Holder',
    'Mahipal Lomror',
  ],
  Shashank: [
    'Quinton De Kock',
    'Umran Malik',
    'Ruturaj Gaikwad',
    'Aiden Markram',
    'Kuldeep Yadav',
    'T Natarajan',
    'Simran Singh',
    'Wriddhiman Saha',
    'Rahul Chahar',
    'Sam Curran',
    'Mitchell Marsh',
    'Jitesh Sharma',
    'Kyle Mayers',
    'Raj Angad Bawa',
    'Sai Sudharsan',
  ],
  Anand: [
    'MS Dhoni',
    'Sisanda Magala',
    'Shubman Gill',
    'David Warner',
    'Mohammad Shami',
    'Avesh Khan',
    'Shimron Hetmyer',
    'Mandeep Singh',
    'Umesh Yadav',
    'Cameron Green',
    'Odean Smith',
    'Ishant Sharma',
    'Manan Vohra',
    'Shivam Singh',
  ],
  Naveen: [
    'Nicholas Pooran',
    'Kagiso Rabada',
    'Faf Du Plessis',
    'Nitish Rana',
    'Rahul Tewatia',
    'Deepak Chahar',
    'Devdutt Padikkal',
    'Jagadeesan Narayan',
    'Jason Behrendorff',
    'Jofra Archer',
    'Shivam Dube',
    'Axar Patel',
    'Mayank Markande',
    'Shahbaz Ahmed',
    'Chris Jordan',
  ],
  Vasikaran: [
    'Heinrich Klaasen',
    'Yuzvendra Chahal',
    'Mayank Agarwal',
    'Liam Livingstone',
    'Shardul Thakur',
    'Harshal Patel',
    'Riyan Parag',
    'Abdul Samad',
    'Kartik Tyagi',
    'Hardik Pandya',
    'Washington Sundar',
    'Krunal Pandya',
    'Adil Rashid',
    'Rovman Powell',
    'Ajinkya Rahane',
  ],
};

interface MasterData {
  [name: string]: string[];
}
