export const masterData: MasterData = {
  'Dinesh Khanna': [
    'K L Rahul',
    'Trent Boult',
    'Suryakumar Yadav',
    'Tilak Varma',
    'Ravi Bishnoi',
    'Bhuvneshwar Kumar',
    'Tim David',
    'Sarfaraz Khan',
    'Reece Topley',
    'Wanindu Hasaranga',
    'Marcus Stoinis',
    'Ramandeep Singh',
    'Kuldeep Sen',
    'Arshad Khan',
    'Rahmanullah Gurbaz',
  ],
  Yeshwant: [
    'Ishan Kishan',
    'Varun Chakaravarthy',
    'Virat Kohli',
    'Devon Conway',
    'Anrich Nortje',
    'Chetan Sakariya',
    'Matthew Wade',
    'Rajat Patidar',
    'Maheesh Theekshana',
    'Andre Russell',
    'Venkatesh Iyer',
    'Harpreet Brar',
    'Navdeep Saini',
    'Hrithik Shokeen',
    'Aman Khan',
  ],
  Siddharth: [
    'Sanju Samson',
    'Sunil Narine',
    'Prithvi Shaw',
    'David Miller',
    'Josh Hazlewood',
    'Sai Kishore',
    'Shahrukh Khan',
    'Ambati Rayudu',
    'Shivam Mavi',
    'Glenn Maxwell',
    'Moeen Ali',
    'Anuj Rawat',
    'Jaydev Unadkat',
    'Murugan Ashwin',
  ],
  Roshan: [
    'Dinesh Karthik',
    'Rashid Khan',
    'Rohit Sharma',
    'Rahul Tripathi',
    'Arshdeep Singh',
    'Mustafizur Rahman',
    'Manish Pandey',
    'Bhanuka Rajapaksa',
    'Amit Mishra',
    'Ben Stokes',
    'Shakib Al Hasan',
    'Ravichandran Ashwin',
    'Ayush Badoni',
    'Akash Deep',
    'Mark Wood',
  ],
  'Kiren Kumar': [
    'Jos Buttler',
    'Mohammed Siraj',
    'Shikhar Dhawan',
    'Yashasvi Jaiswal',
    'Lockie Ferguson',
    'Alzarri Joseph',
    'Rinku Singh',
    'Harry Brook',
    'Khaleel Ahmed',
    'Ravindra Jadeja',
    'Deepak Hooda',
    'Abhishek Sharma',
    'Jason Holder',
    'Mahipal Lomror',
  ],
  Shashank: [
    'Quinton De Kock',
    'Umran Malik',
    'Ruturaj Gaikwad',
    'Aiden Markram',
    'Kuldeep Yadav',
    'T Natarajan',
    'Simran Singh',
    'Wriddhiman Saha',
    'Rahul Chahar',
    'Sam Curran',
    'Mitchell Marsh',
    'Jitesh Sharma',
    'Kyle Mayers',
    'Raj Angad Bawa',
    'Sai Sudarshan',
  ],
  Anand: [
    'MS Dhoni',
    'Sisanda Magala',
    'Shubman Gill',
    'David Warner',
    'Mohammad Shami',
    'Avesh Khan',
    'Shimron Hetmyer',
    'Mandeep Singh',
    'Umesh Yadav',
    'Cameron Green',
    'Odean Smith',
    'Ishant Sharma',
    'Manan Vohra',
    'Shivam Singh',
  ],
  Naveen: [
    'Nicholas Pooran',
    'Kagiso Rabada',
    'Faf Du Plessis',
    'Nitish Rana',
    'Rahul Tewatia',
    'Deepak Chahar',
    'Devdutt Padikkal',
    'Jagadeesan Narayan',
    'Jason Behrendorff',
    'Jofra Archer',
    'Shivam Dube',
    'Axar Patel',
    'Mayank Markande',
    'Shahbaz Ahamad',
  ],
  Vasikaran: [
    'Heinrich Klaasen',
    'Yuzvendra Chahal',
    'Mayank Agarwal',
    'Liam Livingstone',
    'Shardul Thakur',
    'Harshal Patel',
    'Riyan Parag',
    'Abdul Samad',
    'Kartik Tyagi',
    'Hardik Pandya',
    'Washington Sundar',
    'Krunal Pandya',
    'Adil Rashid',
    'Rovman Powell',
  ],
};

interface MasterData {
  [name: string]: string[];
}
